// 2026-09-25 current-lineup roster. Add one JPG per idol using the image filename below.
// Keep ids stable after publishing so saved progress continues to work.
const IDOLS = [
  { id: 'bts_jin', name: 'JIN', group: 'BTS', image: 'images1/bts_jin.jpg' },
  { id: 'bts_suga', name: 'SUGA', group: 'BTS', image: 'images1/bts_suga.jpg' },
  { id: 'bts_j-hope', name: 'J-HOPE', group: 'BTS', image: 'images1/bts_j-hope.jpg' },
  { id: 'bts_rm', name: 'RM', group: 'BTS', image: 'images1/bts_rm.jpg' },
  { id: 'bts_jimin', name: 'JIMIN', group: 'BTS', image: 'images1/bts_jimin.jpg' },
  { id: 'bts_v', name: 'V', group: 'BTS', image: 'images1/bts_v.jpg' },
  { id: 'bts_jung-kook', name: 'JUNG KOOK', group: 'BTS', image: 'images1/bts_jung-kook.jpg' },
  { id: 'seventeen_s-coups', name: 'S.COUPS', group: 'SEVENTEEN', image: 'images2/seventeen_s-coups.jpg' },
  { id: 'seventeen_jeonghan', name: 'JEONGHAN', group: 'SEVENTEEN', image: 'images2/seventeen_jeonghan.jpg' },
  { id: 'seventeen_joshua', name: 'JOSHUA', group: 'SEVENTEEN', image: 'images2/seventeen_joshua.jpg' },
  { id: 'seventeen_jun', name: 'JUN', group: 'SEVENTEEN', image: 'images2/seventeen_jun.jpg' },
  { id: 'seventeen_hoshi', name: 'HOSHI', group: 'SEVENTEEN', image: 'images2/seventeen_hoshi.jpg' },
  { id: 'seventeen_wonwoo', name: 'WONWOO', group: 'SEVENTEEN', image: 'images2/seventeen_wonwoo.jpg' },
  { id: 'seventeen_woozi', name: 'WOOZI', group: 'SEVENTEEN', image: 'images2/seventeen_woozi.jpg' },
  { id: 'seventeen_the-8', name: 'THE 8', group: 'SEVENTEEN', image: 'images2/seventeen_the-8.jpg' },
  { id: 'seventeen_mingyu', name: 'MINGYU', group: 'SEVENTEEN', image: 'images2/seventeen_mingyu.jpg' },
  { id: 'seventeen_dk', name: 'DK', group: 'SEVENTEEN', image: 'images2/seventeen_dk.jpg' },
  { id: 'seventeen_seungkwan', name: 'SEUNGKWAN', group: 'SEVENTEEN', image: 'images2/seventeen_seungkwan.jpg' },
  { id: 'seventeen_vernon', name: 'VERNON', group: 'SEVENTEEN', image: 'images2/seventeen_vernon.jpg' },
  { id: 'seventeen_dino', name: 'DINO', group: 'SEVENTEEN', image: 'images2/seventeen_dino.jpg' },
  { id: 'stray-kids_bang-chan', name: 'BANG CHAN', group: 'Stray Kids', image: 'images2/stray-kids_bang-chan.jpg' },
  { id: 'stray-kids_lee-know', name: 'LEE KNOW', group: 'Stray Kids', image: 'images2/stray-kids_lee-know.jpg' },
  { id: 'stray-kids_changbin', name: 'CHANGBIN', group: 'Stray Kids', image: 'images2/stray-kids_changbin.jpg' },
  { id: 'stray-kids_hyunjin', name: 'HYUNJIN', group: 'Stray Kids', image: 'images2/stray-kids_hyunjin.jpg' },
  { id: 'stray-kids_han', name: 'HAN', group: 'Stray Kids', image: 'images2/stray-kids_han.jpg' },
  { id: 'stray-kids_felix', name: 'FELIX', group: 'Stray Kids', image: 'images2/stray-kids_felix.jpg' },
  { id: 'stray-kids_seungmin', name: 'SEUNGMIN', group: 'Stray Kids', image: 'images2/stray-kids_seungmin.jpg' },
  { id: 'stray-kids_i-n', name: 'I.N', group: 'Stray Kids', image: 'images2/stray-kids_i-n.jpg' },
  { id: 'txt_soobin', name: 'SOOBIN', group: 'TXT', image: 'images2/txt_soobin.jpg' },
  { id: 'txt_yeonjun', name: 'YEONJUN', group: 'TXT', image: 'images2/txt_yeonjun.jpg' },
  { id: 'txt_beomgyu', name: 'BEOMGYU', group: 'TXT', image: 'images2/txt_beomgyu.jpg' },
  { id: 'txt_taehyun', name: 'TAEHYUN', group: 'TXT', image: 'images2/txt_taehyun.jpg' },
  { id: 'txt_hueningkai', name: 'HUENINGKAI', group: 'TXT', image: 'images2/txt_hueningkai.jpg' },
  { id: 'enhypen_jungwon', name: 'JUNGWON', group: 'ENHYPEN', image: 'images1/enhypen_jungwon.jpg' },
  { id: 'enhypen_jay', name: 'JAY', group: 'ENHYPEN', image: 'images1/enhypen_jay.jpg' },
  { id: 'enhypen_jake', name: 'JAKE', group: 'ENHYPEN', image: 'images1/enhypen_jake.jpg' },
  { id: 'enhypen_sunghoon', name: 'SUNGHOON', group: 'ENHYPEN', image: 'images1/enhypen_sunghoon.jpg' },
  { id: 'enhypen_sunoo', name: 'SUNOO', group: 'ENHYPEN', image: 'images1/enhypen_sunoo.jpg' },
  { id: 'enhypen_ni-ki', name: 'NI-KI', group: 'ENHYPEN', image: 'images1/enhypen_ni-ki.jpg' },
  { id: 'ateez_hongjoong', name: 'HONGJOONG', group: 'ATEEZ', image: 'images1/ateez_hongjoong.jpg' },
  { id: 'ateez_seonghwa', name: 'SEONGHWA', group: 'ATEEZ', image: 'images1/ateez_seonghwa.jpg' },
  { id: 'ateez_yunho', name: 'YUNHO', group: 'ATEEZ', image: 'images1/ateez_yunho.jpg' },
  { id: 'ateez_yeosang', name: 'YEOSANG', group: 'ATEEZ', image: 'images1/ateez_yeosang.jpg' },
  { id: 'ateez_san', name: 'SAN', group: 'ATEEZ', image: 'images1/ateez_san.jpg' },
  { id: 'ateez_mingi', name: 'MINGI', group: 'ATEEZ', image: 'images1/ateez_mingi.jpg' },
  { id: 'ateez_wooyoung', name: 'WOOYOUNG', group: 'ATEEZ', image: 'images1/ateez_wooyoung.jpg' },
  { id: 'ateez_jongho', name: 'JONGHO', group: 'ATEEZ', image: 'images1/ateez_jongho.jpg' },
  { id: 'nct-wish_sion', name: 'SION', group: 'NCT WISH', image: 'images2/nct-wish_sion.jpg' },
  { id: 'nct-wish_riku', name: 'RIKU', group: 'NCT WISH', image: 'images2/nct-wish_riku.jpg' },
  { id: 'nct-wish_yushi', name: 'YUSHI', group: 'NCT WISH', image: 'images2/nct-wish_yushi.jpg' },
  { id: 'nct-wish_jaehee', name: 'JAEHEE', group: 'NCT WISH', image: 'images2/nct-wish_jaehee.jpg' },
  { id: 'nct-wish_ryo', name: 'RYO', group: 'NCT WISH', image: 'images2/nct-wish_ryo.jpg' },
  { id: 'nct-wish_sakuya', name: 'SAKUYA', group: 'NCT WISH', image: 'images2/nct-wish_sakuya.jpg' },
  { id: 'riize_shotaro', name: 'SHOTARO', group: 'RIIZE', image: 'images2/riize_shotaro.jpg' },
  { id: 'riize_eunseok', name: 'EUNSEOK', group: 'RIIZE', image: 'images2/riize_eunseok.jpg' },
  { id: 'riize_sungchan', name: 'SUNGCHAN', group: 'RIIZE', image: 'images2/riize_sungchan.jpg' },
  { id: 'riize_wonbin', name: 'WONBIN', group: 'RIIZE', image: 'images2/riize_wonbin.jpg' },
  { id: 'riize_sohee', name: 'SOHEE', group: 'RIIZE', image: 'images2/riize_sohee.jpg' },
  { id: 'riize_anton', name: 'ANTON', group: 'RIIZE', image: 'images2/riize_anton.jpg' },
  { id: 'boynextdoor_sungho', name: 'SUNGHO', group: 'BOYNEXTDOOR', image: 'images1/boynextdoor_sungho.jpg' },
  { id: 'boynextdoor_riwoo', name: 'RIWOO', group: 'BOYNEXTDOOR', image: 'images1/boynextdoor_riwoo.jpg' },
  { id: 'boynextdoor_jaehyun', name: 'JAEHYUN', group: 'BOYNEXTDOOR', image: 'images1/boynextdoor_jaehyun.jpg' },
  { id: 'boynextdoor_taesan', name: 'TAESAN', group: 'BOYNEXTDOOR', image: 'images1/boynextdoor_taesan.jpg' },
  { id: 'boynextdoor_leehan', name: 'LEEHAN', group: 'BOYNEXTDOOR', image: 'images1/boynextdoor_leehan.jpg' },
  { id: 'boynextdoor_woonhak', name: 'WOONHAK', group: 'BOYNEXTDOOR', image: 'images1/boynextdoor_woonhak.jpg' },
  { id: 'tws_shinyu', name: 'SHINYU', group: 'TWS', image: 'images2/tws_shinyu.jpg' },
  { id: 'tws_dohoon', name: 'DOHOON', group: 'TWS', image: 'images2/tws_dohoon.jpg' },
  { id: 'tws_youngjae', name: 'YOUNGJAE', group: 'TWS', image: 'images2/tws_youngjae.jpg' },
  { id: 'tws_hanjin', name: 'HANJIN', group: 'TWS', image: 'images2/tws_hanjin.jpg' },
  { id: 'tws_jihoon', name: 'JIHOON', group: 'TWS', image: 'images2/tws_jihoon.jpg' },
  { id: 'tws_kyungmin', name: 'KYUNGMIN', group: 'TWS', image: 'images2/tws_kyungmin.jpg' },
  { id: 'zerobaseone_sung-han-bin', name: 'SUNG HAN BIN', group: 'ZEROBASEONE', image: 'images2/zerobaseone_sung-han-bin.jpg' },
  { id: 'zerobaseone_kim-ji-woong', name: 'KIM JI WOONG', group: 'ZEROBASEONE', image: 'images2/zerobaseone_kim-ji-woong.jpg' },
  { id: 'zerobaseone_seok-matthew', name: 'SEOK MATTHEW', group: 'ZEROBASEONE', image: 'images2/zerobaseone_seok-matthew.jpg' },
  { id: 'zerobaseone_kim-tae-rae', name: 'KIM TAE RAE', group: 'ZEROBASEONE', image: 'images2/zerobaseone_kim-tae-rae.jpg' },
  { id: 'zerobaseone_park-gun-wook', name: 'PARK GUN WOOK', group: 'ZEROBASEONE', image: 'images2/zerobaseone_park-gun-wook.jpg' },
  { id: 'cortis_martin', name: 'MARTIN', group: 'CORTIS', image: 'images1/cortis_martin.jpg' },
  { id: 'cortis_james', name: 'JAMES', group: 'CORTIS', image: 'images1/cortis_james.jpg' },
  { id: 'cortis_juhoon', name: 'JUHOON', group: 'CORTIS', image: 'images1/cortis_juhoon.jpg' },
  { id: 'cortis_seonghyeon', name: 'SEONGHYEON', group: 'CORTIS', image: 'images1/cortis_seonghyeon.jpg' },
  { id: 'cortis_keonho', name: 'KEONHO', group: 'CORTIS', image: 'images1/cortis_keonho.jpg' },
  { id: 'alpha-drive-one_leo', name: 'LEO', group: 'ALPHA DRIVE ONE', image: 'images1/alpha-drive-one_leo.jpg' },
  { id: 'alpha-drive-one_junseo', name: 'JUNSEO', group: 'ALPHA DRIVE ONE', image: 'images1/alpha-drive-one_junseo.jpg' },
  { id: 'alpha-drive-one_arno', name: 'ARNO', group: 'ALPHA DRIVE ONE', image: 'images1/alpha-drive-one_arno.jpg' },
  { id: 'alpha-drive-one_geonwoo', name: 'GEONWOO', group: 'ALPHA DRIVE ONE', image: 'images1/alpha-drive-one_geonwoo.jpg' },
  { id: 'alpha-drive-one_sangwon', name: 'SANGWON', group: 'ALPHA DRIVE ONE', image: 'images1/alpha-drive-one_sangwon.jpg' },
  { id: 'alpha-drive-one_xinlong', name: 'XINLONG', group: 'ALPHA DRIVE ONE', image: 'images1/alpha-drive-one_xinlong.jpg' },
  { id: 'alpha-drive-one_anxin', name: 'ANXIN', group: 'ALPHA DRIVE ONE', image: 'images1/alpha-drive-one_anxin.jpg' },
  { id: 'alpha-drive-one_sanghyeon', name: 'SANGHYEON', group: 'ALPHA DRIVE ONE', image: 'images1/alpha-drive-one_sanghyeon.jpg' },
  { id: 'treasure_choi-hyun-suk', name: 'CHOI HYUN SUK', group: 'TREASURE', image: 'images2/treasure_choi-hyun-suk.jpg' },
  { id: 'treasure_jihoon', name: 'JIHOON', group: 'TREASURE', image: 'images2/treasure_jihoon.jpg' },
  { id: 'treasure_yoshi', name: 'YOSHI', group: 'TREASURE', image: 'images2/treasure_yoshi.jpg' },
  { id: 'treasure_junkyu', name: 'JUNKYU', group: 'TREASURE', image: 'images2/treasure_junkyu.jpg' },
  { id: 'treasure_yoon-jae-hyuk', name: 'YOON JAE HYUK', group: 'TREASURE', image: 'images2/treasure_yoon-jae-hyuk.jpg' },
  { id: 'treasure_asahi', name: 'ASAHI', group: 'TREASURE', image: 'images2/treasure_asahi.jpg' },
  { id: 'treasure_doyoung', name: 'DOYOUNG', group: 'TREASURE', image: 'images2/treasure_doyoung.jpg' },
  { id: 'treasure_haruto', name: 'HARUTO', group: 'TREASURE', image: 'images2/treasure_haruto.jpg' },
  { id: 'treasure_park-jeong-woo', name: 'PARK JEONG WOO', group: 'TREASURE', image: 'images2/treasure_park-jeong-woo.jpg' },
  { id: 'treasure_so-jung-hwan', name: 'SO JUNG HWAN', group: 'TREASURE', image: 'images2/treasure_so-jung-hwan.jpg' },
  { id: 'exo_suho', name: 'SUHO', group: 'EXO', image: 'images1/exo_suho.jpg' },
  { id: 'exo_lay', name: 'LAY', group: 'EXO', image: 'images1/exo_lay.jpg' },
  { id: 'exo_chanyeol', name: 'CHANYEOL', group: 'EXO', image: 'images1/exo_chanyeol.jpg' },
  { id: 'exo_d-o', name: 'D.O.', group: 'EXO', image: 'images1/exo_d-o.jpg' },
  { id: 'exo_kai', name: 'KAI', group: 'EXO', image: 'images1/exo_kai.jpg' },
  { id: 'exo_sehun', name: 'SEHUN', group: 'EXO', image: 'images1/exo_sehun.jpg' },
  { id: 'astro_mj', name: 'MJ', group: 'ASTRO', image: 'images1/astro_mj.jpg' },
  { id: 'astro_jinjin', name: 'JINJIN', group: 'ASTRO', image: 'images1/astro_jinjin.jpg' },
  { id: 'astro_cha-eun-woo', name: 'CHA EUN-WOO', group: 'ASTRO', image: 'images1/astro_cha-eun-woo.jpg' },
  { id: 'astro_yoon-san-ha', name: 'YOON SAN-HA', group: 'ASTRO', image: 'images1/astro_yoon-san-ha.jpg' },
  { id: 'and2ble_zhang-hao', name: 'ZHANG HAO', group: 'AND2BLE', image: 'images1/and2ble_zhang-hao.jpg' },
  { id: 'and2ble_yoo-seungeon', name: 'YOO SEUNGEON', group: 'AND2BLE', image: 'images1/and2ble_yoo-seungeon.jpg' },
  { id: 'and2ble_ricky', name: 'RICKY', group: 'AND2BLE', image: 'images1/and2ble_ricky.jpg' },
  { id: 'and2ble_kim-gyuvin', name: 'KIM GYUVIN', group: 'AND2BLE', image: 'images1/and2ble_kim-gyuvin.jpg' },
  { id: 'and2ble_han-yujin', name: 'HAN YUJIN', group: 'AND2BLE', image: 'images1/and2ble_han-yujin.jpg' },
  { id: 'kickflip_kyehoon', name: 'KYEHOON', group: 'KickFlip', image: 'images2/kickflip_kyehoon.jpg' },
  { id: 'kickflip_amaru', name: 'AMARU', group: 'KickFlip', image: 'images2/kickflip_amaru.jpg' },
  { id: 'kickflip_donghwa', name: 'DONGHWA', group: 'KickFlip', image: 'images2/kickflip_donghwa.jpg' },
  { id: 'kickflip_juwang', name: 'JUWANG', group: 'KickFlip', image: 'images2/kickflip_juwang.jpg' },
  { id: 'kickflip_minje', name: 'MINJE', group: 'KickFlip', image: 'images2/kickflip_minje.jpg' },
  { id: 'kickflip_keiju', name: 'KEIJU', group: 'KickFlip', image: 'images2/kickflip_keiju.jpg' },
  { id: 'kickflip_donghyeon', name: 'DONGHYEON', group: 'KickFlip', image: 'images2/kickflip_donghyeon.jpg' },
  { id: 'idid_jang-yonghoon', name: 'JANG YONGHOON', group: 'IDID', image: 'images2/idid_jang-yonghoon.jpg' },
  { id: 'idid_kim-minjae', name: 'KIM MINJAE', group: 'IDID', image: 'images2/idid_kim-minjae.jpg' },
  { id: 'idid_park-wonbin', name: 'PARK WONBIN', group: 'IDID', image: 'images2/idid_park-wonbin.jpg' },
  { id: 'idid_chu-yoochan', name: 'CHU YOOCHAN', group: 'IDID', image: 'images1/idid_chu-yoochan.jpg' },
  { id: 'idid_park-seonghyeon', name: 'PARK SEONGHYEON', group: 'IDID', image: 'images2/idid_park-seonghyeon.jpg' },
  { id: 'idid_baek-junhyuk', name: 'BAEK JUNHYUK', group: 'IDID', image: 'images1/idid_baek-junhyuk.jpg' },
  { id: 'idid_jeong-semin', name: 'JEONG SEMIN', group: 'IDID', image: 'images2/idid_jeong-semin.jpg' },
  { id: 'ahof_steven', name: 'STEVEN', group: 'AHOF', image: 'images1/ahof_steven.jpg' },
  { id: 'ahof_jeongwoo', name: 'JEONGWOO', group: 'AHOF', image: 'images1/ahof_jeongwoo.jpg' },
  { id: 'ahof_woongki', name: 'WOONGKI', group: 'AHOF', image: 'images1/ahof_woongki.jpg' },
  { id: 'ahof_shuaibo', name: 'SHUAIBO', group: 'AHOF', image: 'images1/ahof_shuaibo.jpg' },
  { id: 'ahof_han', name: 'HAN', group: 'AHOF', image: 'images1/ahof_han.jpg' },
  { id: 'ahof_jl', name: 'JL', group: 'AHOF', image: 'images1/ahof_jl.jpg' },
  { id: 'ahof_juwon', name: 'JUWON', group: 'AHOF', image: 'images1/ahof_juwon.jpg' },
  { id: 'ahof_chih-en', name: 'CHIH EN', group: 'AHOF', image: 'images1/ahof_chih-en.jpg' },
  { id: 'ahof_daisuke', name: 'DAISUKE', group: 'AHOF', image: 'images1/ahof_daisuke.jpg' },
  { id: 'andteam_ej', name: 'EJ', group: '&TEAM', image: 'images1/andteam_ej.jpg' },
  { id: 'andteam_fuma', name: 'FUMA', group: '&TEAM', image: 'images1/andteam_fuma.jpg' },
  { id: 'andteam_k', name: 'K', group: '&TEAM', image: 'images1/andteam_k.jpg' },
  { id: 'andteam_nicholas', name: 'NICHOLAS', group: '&TEAM', image: 'images1/andteam_nicholas.jpg' },
  { id: 'andteam_yuma', name: 'YUMA', group: '&TEAM', image: 'images1/andteam_yuma.jpg' },
  { id: 'andteam_jo', name: 'JO', group: '&TEAM', image: 'images1/andteam_jo.jpg' },
  { id: 'andteam_harua', name: 'HARUA', group: '&TEAM', image: 'images1/andteam_harua.jpg' },
  { id: 'andteam_taki', name: 'TAKI', group: '&TEAM', image: 'images1/andteam_taki.jpg' },
  { id: 'andteam_maki', name: 'MAKI', group: '&TEAM', image: 'images1/andteam_maki.jpg' },
  { id: 'solo_evan-heeseung', name: 'EVAN (HEESEUNG)', group: 'SOLO', image: 'images2/solo_evan-heeseung.jpg' },
  { id: 'solo_baekhyun', name: 'BAEKHYUN', group: 'SOLO', image: 'images2/solo_baekhyun.jpg' },
  { id: 'solo_chen', name: 'CHEN', group: 'SOLO', image: 'images2/solo_chen.jpg' },
  { id: 'solo_xiumin', name: 'XIUMIN', group: 'SOLO', image: 'images2/solo_xiumin.jpg' },
];


// Result-card metadata. MV choices are a fixed September 2026 snapshot.
// You can update a video later by changing only title / youtubeId below.
window.GROUP_INFO = {
  'BTS': { debut: '2013', mvTitle: 'Dynamite', youtubeId: 'gdZLi9oWNZg' },
  'SEVENTEEN': { debut: '2015', mvTitle: "Don't Wanna Cry", youtubeId: 'zEkg4GBQumc' },
  'Stray Kids': { debut: '2018', mvTitle: "God's Menu", youtubeId: 'TQTlCHxyuu8' },
  'TXT': { debut: '2019', mvTitle: 'Blue Hour', youtubeId: 'Vd9QkWsd5p4' },
  'ENHYPEN': { debut: '2020', mvTitle: 'Bite Me', youtubeId: 'wXFLzODIdUI' },
  'ATEEZ': { debut: '2018', mvTitle: 'BOUNCY (K-HOT CHILLI PEPPERS)', youtubeId: 'U0G5OA6ZH5w' },
  'NCT WISH': { debut: '2024', mvTitle: 'WISH (Korean Ver.)', youtubeId: 'hvQZs3k6Ytk' },
  'RIIZE': { debut: '2023', mvTitle: 'Love 119', youtubeId: '0TAAUWHo4Ec' },
  'BOYNEXTDOOR': { debut: '2023', mvTitle: 'Earth, Wind & Fire', youtubeId: 'u9nP3qXQA4o' },
  'TWS': { debut: '2024', mvTitle: 'plot twist', youtubeId: 'hVAc1Vf2ITU' },
  'ZEROBASEONE': { debut: '2023', mvTitle: 'In Bloom', youtubeId: 'trzeUClQIIg' },
  'CORTIS': { debut: '2025', mvTitle: 'GO!', youtubeId: 'WXS-o57VJ5w' },
  'ALPHA DRIVE ONE': { debut: '2026', mvTitle: 'FREAK ALARM', youtubeId: 'P8VVnopM610' },
  'TREASURE': { debut: '2020', mvTitle: 'JIKJIN', youtubeId: 'ZJaKdBBzUYk' },
  'EXO': { debut: '2012', mvTitle: 'Love Shot', youtubeId: 'pSudEWBAYRE' },
  'ASTRO': { debut: '2016', mvTitle: 'Crazy Sexy Cool', youtubeId: 'xeUx0AN2kCA' },
  'AND2BLE': { debut: '2026', mvTitle: 'Curious', youtubeId: 'm6kmpiOsLVk' },
  'KickFlip': { debut: '2025', mvTitle: 'Mama Said', youtubeId: 'JY0UTOgh8M8' },
  'IDID': { debut: '2026', mvTitle: 'FLY!', youtubeId: 'fcfv_p_NWx8' },
  'AHOF': { debut: '2025', mvTitle: 'RUN TO YOU', youtubeId: 'OhbMVYVNo40' },
  '&TEAM': { debut: '2022', mvTitle: 'We on Fire', youtubeId: '8hU6P7MmRyk' }
};

window.SOLO_INFO = {
  'solo_evan-heeseung': {
    displayAffiliation: 'SOLO', debut: '2026', birthday: '2001.10.15', nationality: '韓国', height: '181.5 cm',
    mvTitle: 'Ride or Die', youtubeId: 'CsGENgLpyaw'
  },
  'solo_baekhyun': {
    displayAffiliation: 'SOLO', debut: '2019', birthday: '1992.05.06', nationality: '韓国', height: '174 cm',
    mvTitle: 'Candy', youtubeId: 'gmgcRWxhmqY'
  },
  'solo_chen': {
    displayAffiliation: 'SOLO', debut: '2019', birthday: '1992.09.21', nationality: '韓国', height: '173 cm',
    mvTitle: 'Beautiful goodbye', youtubeId: 'JrOrlhjIYVk'
  },
  'solo_xiumin': {
    displayAffiliation: 'SOLO', debut: '2022', birthday: '1990.03.26', nationality: '韓国', height: '173 cm',
    mvTitle: 'Brand New', youtubeId: 'pU8Gu5aOWZ0'
  }
};

// Complete profile details for the No.1 card (September 2026 snapshot).
// Heights use publicly listed profile values; “非公開” is shown where no reliable public value is listed.
window.IDOL_PROFILES = {
  'bts_jin': { birthday: '1992.12.04', nationality: '韓国', height: '179.5 cm' },
  'bts_suga': { birthday: '1993.03.09', nationality: '韓国', height: '174 cm' },
  'bts_j-hope': { birthday: '1994.02.18', nationality: '韓国', height: '177 cm' },
  'bts_rm': { birthday: '1994.09.12', nationality: '韓国', height: '181 cm' },
  'bts_jimin': { birthday: '1995.10.13', nationality: '韓国', height: '174 cm' },
  'bts_v': { birthday: '1995.12.30', nationality: '韓国', height: '179 cm' },
  'bts_jung-kook': { birthday: '1997.09.01', nationality: '韓国', height: '178 cm' },
  'seventeen_s-coups': { birthday: '1995.08.08', nationality: '韓国', height: '178 cm' },
  'seventeen_jeonghan': { birthday: '1995.10.04', nationality: '韓国', height: '178 cm' },
  'seventeen_joshua': { birthday: '1995.12.30', nationality: '韓国系アメリカ', height: '177 cm' },
  'seventeen_jun': { birthday: '1996.06.10', nationality: '中国', height: '182 cm' },
  'seventeen_hoshi': { birthday: '1996.06.15', nationality: '韓国', height: '177 cm' },
  'seventeen_wonwoo': { birthday: '1996.07.17', nationality: '韓国', height: '182 cm' },
  'seventeen_woozi': { birthday: '1996.11.22', nationality: '韓国', height: '166 cm' },
  'seventeen_the-8': { birthday: '1997.11.07', nationality: '中国', height: '180 cm' },
  'seventeen_mingyu': { birthday: '1997.04.06', nationality: '韓国', height: '187 cm' },
  'seventeen_dk': { birthday: '1997.02.18', nationality: '韓国', height: '179 cm' },
  'seventeen_seungkwan': { birthday: '1998.01.16', nationality: '韓国', height: '174 cm' },
  'seventeen_vernon': { birthday: '1998.02.18', nationality: '韓国系アメリカ', height: '178 cm' },
  'seventeen_dino': { birthday: '1999.02.11', nationality: '韓国', height: '174 cm' },
  'stray-kids_bang-chan': { birthday: '1997.10.03', nationality: '韓国系オーストラリア', height: '171 cm' },
  'stray-kids_lee-know': { birthday: '1998.10.25', nationality: '韓国', height: '172 cm' },
  'stray-kids_changbin': { birthday: '1999.08.11', nationality: '韓国', height: '167 cm' },
  'stray-kids_hyunjin': { birthday: '2000.03.20', nationality: '韓国', height: '179 cm' },
  'stray-kids_han': { birthday: '2000.09.14', nationality: '韓国', height: '169 cm' },
  'stray-kids_felix': { birthday: '2000.09.15', nationality: 'オーストラリア', height: '171 cm' },
  'stray-kids_seungmin': { birthday: '2000.09.22', nationality: '韓国', height: '178 cm' },
  'stray-kids_i-n': { birthday: '2001.02.08', nationality: '韓国', height: '172 cm' },
  'txt_soobin': { birthday: '2000.12.05', nationality: '韓国', height: '185 cm' },
  'txt_yeonjun': { birthday: '1999.09.13', nationality: '韓国', height: '181.5 cm' },
  'txt_beomgyu': { birthday: '2001.03.13', nationality: '韓国', height: '180 cm' },
  'txt_taehyun': { birthday: '2002.02.05', nationality: '韓国', height: '177 cm' },
  'txt_hueningkai': { birthday: '2002.08.14', nationality: '韓国・米国', height: '183 cm' },
  'enhypen_jungwon': { birthday: '2004.02.09', nationality: '韓国', height: '175 cm' },
  'enhypen_jay': { birthday: '2002.04.20', nationality: '韓国・米国', height: '180 cm' },
  'enhypen_jake': { birthday: '2002.11.15', nationality: '韓国系オーストラリア', height: '175 cm' },
  'enhypen_sunghoon': { birthday: '2002.12.08', nationality: '韓国', height: '181 cm' },
  'enhypen_sunoo': { birthday: '2003.06.24', nationality: '韓国', height: '177 cm' },
  'enhypen_ni-ki': { birthday: '2005.12.09', nationality: '日本', height: '183 cm' },
  'ateez_hongjoong': { birthday: '1998.11.07', nationality: '韓国', height: '172 cm' },
  'ateez_seonghwa': { birthday: '1998.04.03', nationality: '韓国', height: '178 cm' },
  'ateez_yunho': { birthday: '1999.03.23', nationality: '韓国', height: '186 cm' },
  'ateez_yeosang': { birthday: '1999.06.15', nationality: '韓国', height: '175 cm' },
  'ateez_san': { birthday: '1999.07.10', nationality: '韓国', height: '178 cm' },
  'ateez_mingi': { birthday: '1999.08.09', nationality: '韓国', height: '184 cm' },
  'ateez_wooyoung': { birthday: '1999.11.26', nationality: '韓国', height: '173 cm' },
  'ateez_jongho': { birthday: '2000.10.12', nationality: '韓国', height: '176 cm' },
  'nct-wish_sion': { birthday: '2002.05.11', nationality: '韓国', height: '179 cm' },
  'nct-wish_riku': { birthday: '2003.06.28', nationality: '日本', height: '175 cm' },
  'nct-wish_yushi': { birthday: '2004.04.05', nationality: '日本', height: '175 cm' },
  'nct-wish_jaehee': { birthday: '2005.06.21', nationality: '韓国', height: '185 cm' },
  'nct-wish_ryo': { birthday: '2007.08.04', nationality: '日本', height: '165.4 cm' },
  'nct-wish_sakuya': { birthday: '2007.11.18', nationality: '日本', height: '176 cm' },
  'riize_shotaro': { birthday: '2000.11.25', nationality: '日本', height: '178 cm' },
  'riize_eunseok': { birthday: '2001.03.19', nationality: '韓国', height: '180 cm' },
  'riize_sungchan': { birthday: '2001.09.13', nationality: '韓国', height: '185.6 cm' },
  'riize_wonbin': { birthday: '2002.03.02', nationality: '韓国', height: '176 cm' },
  'riize_sohee': { birthday: '2003.11.21', nationality: '韓国', height: '176 cm' },
  'riize_anton': { birthday: '2004.03.21', nationality: '米国', height: '184 cm' },
  'boynextdoor_sungho': { birthday: '2003.09.04', nationality: '韓国', height: '173 cm' },
  'boynextdoor_riwoo': { birthday: '2003.10.22', nationality: '韓国', height: '170 cm' },
  'boynextdoor_jaehyun': { birthday: '2003.12.04', nationality: '韓国', height: '177 cm' },
  'boynextdoor_taesan': { birthday: '2004.08.10', nationality: '韓国', height: '182 cm' },
  'boynextdoor_leehan': { birthday: '2004.10.20', nationality: '韓国', height: '180 cm' },
  'boynextdoor_woonhak': { birthday: '2006.11.29', nationality: '韓国', height: '182 cm' },
  'tws_shinyu': { birthday: '2003.11.07', nationality: '韓国', height: '182 cm' },
  'tws_dohoon': { birthday: '2005.01.30', nationality: '韓国', height: '182 cm' },
  'tws_youngjae': { birthday: '2005.05.31', nationality: '韓国', height: '181 cm' },
  'tws_hanjin': { birthday: '2006.01.05', nationality: '中国', height: '176 cm' },
  'tws_jihoon': { birthday: '2006.03.28', nationality: '韓国', height: '178.9 cm' },
  'tws_kyungmin': { birthday: '2007.10.02', nationality: '韓国', height: '175 cm' },
  'zerobaseone_sung-han-bin': { birthday: '2001.06.13', nationality: '韓国', height: '179 cm' },
  'zerobaseone_kim-ji-woong': { birthday: '1998.12.14', nationality: '韓国', height: '178 cm' },
  'zerobaseone_seok-matthew': { birthday: '2002.05.28', nationality: '韓国系カナダ', height: '170 cm' },
  'zerobaseone_kim-tae-rae': { birthday: '2002.07.14', nationality: '韓国', height: '174 cm' },
  'zerobaseone_park-gun-wook': { birthday: '2005.01.10', nationality: '韓国', height: '183.9 cm' },
  'cortis_martin': { birthday: '2008.03.20', nationality: '韓国・カナダ', height: '193.4 cm' },
  'cortis_james': { birthday: '2005.10.14', nationality: 'タイ・台湾', height: '176〜178 cm' },
  'cortis_juhoon': { birthday: '2008.01.03', nationality: '韓国', height: '175〜176 cm' },
  'cortis_seonghyeon': { birthday: '2009.01.13', nationality: '韓国', height: '175 cm' },
  'cortis_keonho': { birthday: '2009.02.14', nationality: '韓国', height: '178 cm' },
  'alpha-drive-one_leo': { birthday: '2002.08.22', nationality: 'オーストラリア', height: '179 cm' },
  'alpha-drive-one_junseo': { birthday: '2001.11.20', nationality: '韓国', height: '178.7 cm' },
  'alpha-drive-one_arno': { birthday: '2002.07.07', nationality: '中国', height: '178 cm' },
  'alpha-drive-one_geonwoo': { birthday: '2003.04.11', nationality: '韓国', height: '184.3 cm' },
  'alpha-drive-one_sangwon': { birthday: '2003.05.08', nationality: '韓国', height: '177 cm' },
  'alpha-drive-one_xinlong': { birthday: '2005.03.11', nationality: '中国', height: '177 cm' },
  'alpha-drive-one_anxin': { birthday: '2006.12.25', nationality: '中国', height: '178 cm' },
  'alpha-drive-one_sanghyeon': { birthday: '2007.09.19', nationality: '韓国', height: '180 cm' },
  'treasure_choi-hyun-suk': { birthday: '1999.04.21', nationality: '韓国', height: '171 cm' },
  'treasure_jihoon': { birthday: '2000.03.14', nationality: '韓国', height: '178 cm' },
  'treasure_yoshi': { birthday: '2000.05.15', nationality: '韓国', height: '179 cm' },
  'treasure_junkyu': { birthday: '2000.09.09', nationality: '韓国', height: '178 cm' },
  'treasure_yoon-jae-hyuk': { birthday: '2001.07.23', nationality: '韓国', height: '178 cm' },
  'treasure_asahi': { birthday: '2001.08.20', nationality: '日本', height: '172 cm' },
  'treasure_doyoung': { birthday: '2003.12.04', nationality: '韓国', height: '177 cm' },
  'treasure_haruto': { birthday: '2004.04.05', nationality: '日本', height: '183.2 cm' },
  'treasure_park-jeong-woo': { birthday: '2004.09.28', nationality: '韓国', height: '181 cm' },
  'treasure_so-jung-hwan': { birthday: '2005.02.18', nationality: '韓国', height: '180.3 cm' },
  'exo_suho': { birthday: '1991.05.22', nationality: '韓国', height: '173 cm' },
  'exo_lay': { birthday: '1991.10.07', nationality: '中国', height: '177 cm' },
  'exo_chanyeol': { birthday: '1992.11.27', nationality: '韓国', height: '186 cm' },
  'exo_d-o': { birthday: '1993.01.12', nationality: '韓国', height: '172 cm' },
  'exo_kai': { birthday: '1994.01.14', nationality: '韓国', height: '182 cm' },
  'exo_sehun': { birthday: '1994.04.12', nationality: '韓国', height: '183 cm' },
  'astro_mj': { birthday: '1994.03.05', nationality: '韓国', height: '175 cm' },
  'astro_jinjin': { birthday: '1996.03.15', nationality: '韓国', height: '174 cm' },
  'astro_cha-eun-woo': { birthday: '1997.03.30', nationality: '韓国', height: '183 cm' },
  'astro_yoon-san-ha': { birthday: '2000.03.21', nationality: '韓国', height: '185 cm' },
  'and2ble_zhang-hao': { birthday: '2000.07.25', nationality: '中国', height: '180.5 cm' },
  'and2ble_yoo-seungeon': { birthday: '2004.01.02', nationality: '韓国', height: '180 cm' },
  'and2ble_ricky': { birthday: '2004.05.20', nationality: '中国', height: '184.4 cm' },
  'and2ble_kim-gyuvin': { birthday: '2004.08.30', nationality: '韓国', height: '186 cm' },
  'and2ble_han-yujin': { birthday: '2007.03.20', nationality: '韓国', height: '181 cm' },
  'kickflip_kyehoon': { birthday: '2004.09.16', nationality: '韓国', height: '非公開' },
  'kickflip_amaru': { birthday: '2005.10.21', nationality: '日本', height: '非公開' },
  'kickflip_donghwa': { birthday: '2006.03.11', nationality: '韓国', height: '178 cm' },
  'kickflip_juwang': { birthday: '2006.05.02', nationality: '韓国', height: '183 cm' },
  'kickflip_minje': { birthday: '2006.05.12', nationality: '韓国・ニュージーランド', height: '184 cm' },
  'kickflip_keiju': { birthday: '2006.10.04', nationality: '日本', height: '非公開' },
  'kickflip_donghyeon': { birthday: '2007.03.13', nationality: '韓国', height: '非公開' },
  'idid_jang-yonghoon': { birthday: '2005.04.20', nationality: '韓国', height: '184.2 cm' },
  'idid_kim-minjae': { birthday: '2005.08.17', nationality: '韓国', height: '180 cm' },
  'idid_park-wonbin': { birthday: '2006.04.19', nationality: '韓国', height: '183.8 cm' },
  'idid_chu-yoochan': { birthday: '2006.10.03', nationality: '韓国', height: '175 cm' },
  'idid_park-seonghyeon': { birthday: '2007.10.05', nationality: '韓国', height: '非公開' },
  'idid_baek-junhyuk': { birthday: '2008.06.07', nationality: '韓国', height: '非公開' },
  'idid_jeong-semin': { birthday: '2008.10.10', nationality: '韓国', height: '177 cm' },
  'ahof_steven': { birthday: '2000.01.17', nationality: '韓国系オーストラリア', height: '176 cm' },
  'ahof_jeongwoo': { birthday: '2001.09.06', nationality: '韓国', height: '非公開' },
  'ahof_woongki': { birthday: '2002.04.23', nationality: '韓国', height: '175 cm' },
  'ahof_shuaibo': { birthday: '2002.07.02', nationality: '中国', height: '185 cm' },
  'ahof_han': { birthday: '2003.09.25', nationality: '韓国', height: '非公開' },
  'ahof_jl': { birthday: '2004.04.21', nationality: 'フィリピン', height: '非公開' },
  'ahof_juwon': { birthday: '2006.07.24', nationality: '韓国', height: '非公開' },
  'ahof_chih-en': { birthday: '2006.10.28', nationality: '台湾', height: '176 cm' },
  'ahof_daisuke': { birthday: '2009.12.25', nationality: '日本', height: '171 cm' },
  'andteam_ej': { birthday: '2002.09.07', nationality: '韓国', height: '184 cm' },
  'andteam_fuma': { birthday: '1998.06.29', nationality: '日本', height: '180 cm' },
  'andteam_k': { birthday: '1997.10.21', nationality: '日本', height: '186.5 cm' },
  'andteam_nicholas': { birthday: '2002.07.09', nationality: '台湾', height: '179 cm' },
  'andteam_yuma': { birthday: '2004.02.07', nationality: '日本', height: '174 cm' },
  'andteam_jo': { birthday: '2004.07.08', nationality: '日本', height: '185 cm' },
  'andteam_harua': { birthday: '2005.05.01', nationality: '日本', height: '173 cm' },
  'andteam_taki': { birthday: '2005.05.04', nationality: '日本', height: '176 cm' },
  'andteam_maki': { birthday: '2006.02.17', nationality: '日本・ドイツ', height: '183 cm' },
  'solo_evan-heeseung': { birthday: '2001.10.15', nationality: '韓国', height: '181.5 cm' },
  'solo_baekhyun': { birthday: '1992.05.06', nationality: '韓国', height: '174 cm' },
  'solo_chen': { birthday: '1992.09.21', nationality: '韓国', height: '173 cm' },
  'solo_xiumin': { birthday: '1990.03.26', nationality: '韓国', height: '173 cm' },
};
